@startuml
start

:pygame.init();
:create ekran (1500x800);
:create GameController;
:create GameScreen;
:create BotManager;
:set aktif_oyuncu = 0;
:set el_bekle = False;

repeat
  :screen.fill((0, 100, 0));
  :render_kurallar_button();

  if (kurallar_goster == True) then (evet)
    :kurallari_goster();
    if (Kapat butonu tıklandı?) then (evet)
      :kurallar_goster = False;
    endif
  endif

  if (Tüm eller boş?) then (evet)
    :Oyun bitti (kartlar tükendi);
    stop
  endif

  if (el_bekle == True) then (evet)
    :goster_el_kazanan();
    if (3 saniye geçti?) then (evet)
      :render_continue_button();
      if (Devam Et tıklanır?) then (evet)
        :masa_temizle();
        :aktif_oyuncu = kazanan;
        :el_bekle = False;
      else
        :Devam butonu bekleniyor;
      endif
    else
      :3 saniyeyi bekle;
    endif
  else
    if (aktif_oyuncu == 0) then (Oyuncu)
      :mouse tıklaması bekleniyor;
      if (geçerli kart?) then (evet)
        :kart_at(oyuncu);
        :ilk_tur ayarla;
        :aktif_oyuncu++;
      endif
    else
      if (bot elinde kart var mı?) then (evet)
        :bot_oyna();
        :kart_at(bot);
        :aktif_oyuncu = (aktif_oyuncu + 1) % 4;
      endif
    endif

    if (len(controller.yer) == 4) then (evet)
      :eli_tamamla();
      :kazananı belirle;
      :el sayısını artır;
      :el_bekle = True;
      :başlangıç zamanı kaydet;
    endif
  endif

  :ekranı güncelle (pygame.display.flip());
repeat while (running)

stop
@enduml
